[JENKINS-43472] Add Maven 3.5.0 installation.
jenkinsci/jenkins-test-harness-tools pull request #5
Opened 2017-04-10 16:13 UTC by cyrille-leclerc

[JENKINS-43472](https://issues.jenkins-ci.org/browse/JENKINS-43472) Add Maven 3.5.0 installation.

ℹ️ instead of adding the binaries to the git repository, we use the maven-dependency-plugin to get maven-3.5.0 from Maven Central. This approach could be used to remove large binary files from the git repo (apache-maven 3.0.1 and 3.1.0)

2017-04-10 16:16 UTC, jglick requested changes

2017-04-10 16:16 UTC, jglick commented on pom.xml
> +                        <id>copy-maven-spy-jar</id>
What?

2017-04-10 16:16 UTC, jglick commented
> This approach could be used to remove large binary files from the git repo (apache-maven 3.0.1 and 3.1.0)

Why not do that now too?

2017-04-10 17:30 UTC, cyrille-leclerc commented
>> This approach could be used to remove large binary files from the git repo (apache-maven 3.0.1 and 3.1.0)

> Why not do that now too?

Done

2017-04-11 07:33 UTC, cyrille-leclerc commented on pom.xml
> +                        <id>copy-maven-spy-jar</id>
Fixed

2017-04-13 18:34 UTC, cyrille-leclerc commented
Note urgent as I have implemented a "workaround" in the pipeline-maven-project:

* https://github.com/jenkinsci/pipeline-maven-plugin/blob/87568088f87b5da4e5fbf36a0ccafd3fc1f785f0/jenkins-plugin/src/test/java/org/jvnet/hudson/test/ExtendedToolInstallations.java
* https://github.com/jenkinsci/pipeline-maven-plugin/blob/87568088f87b5da4e5fbf36a0ccafd3fc1f785f0/jenkins-plugin/pom.xml#L253

2017-05-05 21:10 UTC, cyrille-leclerc commented
@reviewbybees

2017-05-05 21:42 UTC, jglick approved these changes

2017-05-05 22:16 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-06-12 07:18 UTC, merged

2017-06-12 07:18 UTC, cyrille-leclerc commented
@jglick could we release this plugin?

2017-06-12 15:22 UTC, jglick commented
Tried to release 2.1 but the connection timed out because it was so gigantic. Noted in a new README that I think this repository needs to be deleted and the use case reconsidered.